version: '2'
services:
  Clevo-Orchestration:
    image: 'node:8.9'
    restart: always
    ports:
      - '1235:3000'
    volumes:
      - './app:/app:rw' # used for dev
      # - ':/app:rw' # dev
#      - 'clevo-orchestration:/app:rw' # staging
      - '/app/node_modules/' # make sure /app/node_modules is empty initially, and detach from oss
    environment:
      - 'PORT=4000'
      - 'MONGO_URI=mongodb://clevoUser:password@ds113505.mlab.com:13505/auth'
      - 'NODE_ENV=dev'
      - 'CLIENT_PORT=3000'
      - 'DEBUG=*,-babel,-*.test'
    labels:
      aliyun.routing.port_3000: orchestration
      aliyun.scale: '2'
    command: bash -c "cd /app && npm install && node app.js"
